"""Juliette crystallographic entrance VAE v54.

This model learns only the crystallographic entrance used by production:
space group and the Ti Wyckoff skeleton.  Lattice parameters, Ti coordinates,
the O skeleton, and O coordinates are generated by chemistry-driven,
symmetry-constrained builders in ``1_train_sample.py``.
"""

import os
import joblib
import numpy as np
import pandas as pd
import torch
from torch.nn import Linear, Module, Parameter, ReLU, Sequential
from torch.nn.functional import cross_entropy
from torch.optim import Adam
from torch.utils.data import DataLoader, TensorDataset

from .data_transformer import DataTransformer
from .base import BaseSynthesizer, random_state


class MLP(Module):
    def __init__(self, input_dim, hidden_dims, output_dim):
        super().__init__()
        layers, dim = [], int(input_dim)
        for width in hidden_dims:
            layers.extend([Linear(dim, int(width)), ReLU()])
            dim = int(width)
        layers.append(Linear(dim, int(output_dim)))
        self.net = Sequential(*layers)

    def forward(self, x):
        return self.net(x)


class Encoder(Module):
    def __init__(self, data_dim, compress_dims, embedding_dim):
        super().__init__()
        layers, dim = [], int(data_dim)
        for width in compress_dims:
            layers.extend([Linear(dim, int(width)), ReLU()])
            dim = int(width)
        self.body = Sequential(*layers)
        self.fc_mu = Linear(dim, int(embedding_dim))
        self.fc_logvar = Linear(dim, int(embedding_dim))

    def forward(self, x):
        h = self.body(x)
        mu = self.fc_mu(h)
        logvar = self.fc_logvar(h)
        std = torch.exp(0.5 * logvar)
        return mu, std, logvar


class Decoder(Module):
    def __init__(self, input_dim, hidden_dims, output_dim):
        super().__init__()
        self.net = MLP(input_dim, hidden_dims, output_dim)
        self.sigma = Parameter(torch.ones(int(output_dim)) * 0.1)

    def forward(self, x):
        return self.net(x), self.sigma


def _activate(logits, output_info_list, temperature=1.0, hard=False, masks=None):
    st, outputs = 0, []
    for column_info in output_info_list:
        for span_info in column_info:
            ed = st + span_info.dim
            span = logits[:, st:ed]
            if span_info.activation_fn != "softmax":
                outputs.append(torch.tanh(span))
            else:
                if masks is not None and (st, ed) in masks:
                    mask = masks[(st, ed)]
                    if mask.shape != span.shape:
                        raise ValueError("Categorical mask shape mismatch.")
                    span = span.masked_fill(~mask, -torch.inf)
                scale = max(float(temperature), 1e-8)
                probs = torch.softmax(span / scale, dim=-1)
                if hard:
                    ids = torch.multinomial(probs, 1).squeeze(1)
                    probs = torch.nn.functional.one_hot(ids, span_info.dim).float()
                outputs.append(probs)
            st = ed
    return torch.cat(outputs, dim=1)


def _discrete_span(transformer, column_name):
    st = 0
    for info in transformer._column_transform_info_list:
        ed = st + info.output_dimensions
        if info.column_name == column_name:
            if info.column_type != "discrete":
                raise ValueError(f"{column_name!r} is not discrete.")
            return st, ed, list(info.transform.dummies)
        st = ed
    raise KeyError(column_name)


def _block_loss(recon_x, x, sigmas, output_info, factor):
    st = 0
    per_row = torch.zeros(x.size(0), device=x.device, dtype=x.dtype)
    for column_info in output_info:
        for span_info in column_info:
            ed = st + span_info.dim
            if span_info.activation_fn != "softmax":
                std = sigmas[st:ed]
                residual = x[:, st:ed] - torch.tanh(recon_x[:, st:ed])
                per_row += ((residual ** 2) / (2 * std ** 2)).sum(1)
                per_row += torch.log(std).sum()
            else:
                per_row += cross_entropy(
                    recon_x[:, st:ed], torch.argmax(x[:, st:ed], dim=-1),
                    reduction="none",
                )
            st = ed
    return per_row.mean() * factor


def _parse_wp_token(token):
    return [int(value) for value in str(token).strip().split("|")]


class FactorizedVAE(BaseSynthesizer):
    """Two-block VAE for the crystallographic entrance S -> W_Ti."""

    def __init__(
        self,
        embedding_dim=128,
        compress_dims=(512, 512),
        decompress_dims=(512, 512),
        context_dim=128,
        l2scale=1e-5,
        batch_size=500,
        epochs=250,
        loss_factor=2.0,
        global_loss_weight=1.0,
        ti_skeleton_loss_weight=1.0,
        kl_weight=1.0,
        kl_warmup_epochs=50,
        predicted_context_start=0.0,
        predicted_context_end=0.8,
        cuda=True,
        verbose=False,
        folder="LEGO-EntranceVAE",
    ):
        self.embedding_dim = int(embedding_dim)
        self.compress_dims = tuple(compress_dims)
        self.decompress_dims = tuple(decompress_dims)
        self.context_dim = int(context_dim)
        self.l2scale = float(l2scale)
        self.batch_size = int(batch_size)
        self.epochs = int(epochs)
        self.loss_factor = float(loss_factor)
        self.global_loss_weight = float(global_loss_weight)
        self.ti_skeleton_loss_weight = float(ti_skeleton_loss_weight)
        self.kl_weight = float(kl_weight)
        self.kl_warmup_epochs = int(kl_warmup_epochs)
        self.predicted_context_start = float(predicted_context_start)
        self.predicted_context_end = float(predicted_context_end)
        self.verbose = bool(verbose)
        self.root_folder = folder
        device = "cpu" if not cuda or not torch.cuda.is_available() else (
            cuda if isinstance(cuda, str) else "cuda"
        )
        self._device = torch.device(device)
        self.model_folder = os.path.join(folder, "models")
        os.makedirs(self.model_folder, exist_ok=True)

    def _context_probability(self, epoch):
        if self.epochs <= 1:
            return self.predicted_context_end
        f = epoch / float(self.epochs - 1)
        return self.predicted_context_start + f * (
            self.predicted_context_end - self.predicted_context_start
        )

    @staticmethod
    def _mix_context(true_x, predicted_x, probability):
        if probability <= 0:
            return true_x
        if probability >= 1:
            return predicted_x
        mask = torch.rand(true_x.size(0), 1, device=true_x.device) < probability
        return torch.where(mask, predicted_x, true_x)

    def _build_models(self, global_dim, ti_dim):
        total_dim = global_dim + ti_dim
        self.encoder = Encoder(total_dim, self.compress_dims, self.embedding_dim).to(self._device)
        self.global_decoder = Decoder(
            self.embedding_dim, self.decompress_dims, global_dim
        ).to(self._device)
        self.global_context_encoder = MLP(
            global_dim, (self.context_dim,), self.context_dim
        ).to(self._device)
        self.ti_skeleton_decoder = Decoder(
            self.embedding_dim + self.context_dim, self.decompress_dims, ti_dim
        ).to(self._device)

    def _all_modules(self):
        return [
            self.encoder,
            self.global_decoder,
            self.global_context_encoder,
            self.ti_skeleton_decoder,
        ]

    def save(self, filepath):
        names = [
            "encoder",
            "global_decoder",
            "global_context_encoder",
            "ti_skeleton_decoder",
            "global_transformer",
            "ti_transformer",
            "ti_skeleton_span",
        ]
        state = {name: getattr(self, name) for name in names}
        state["device"] = str(self._device)
        state["config"] = {
            "architecture": "crystallographic_entrance_v54",
            "production_outputs": ["spg", "ti_skeleton_token"],
        }
        joblib.dump(state, filepath)

    def load(self, filepath):
        state = joblib.load(filepath)
        for name, value in state.items():
            if name not in {"device", "config"}:
                setattr(self, name, value)
        self._device = torch.device(state.get("device", "cpu"))
        for module in self._all_modules():
            module.to(self._device)
        return self

    def set_device(self, device):
        self._device = torch.device(device)
        for module in self._all_modules():
            module.to(self._device)
        return self

    @random_state
    def fit(
        self,
        global_data,
        ti_data,
        global_discrete_columns=(),
        ti_discrete_columns=("ti_skeleton_token",),
    ):
        if len(global_data) != len(ti_data):
            raise ValueError("Global and Ti-skeleton blocks must have equal row counts.")

        self.global_transformer = DataTransformer()
        self.ti_transformer = DataTransformer()
        self.global_transformer.fit(global_data, global_discrete_columns)
        self.ti_transformer.fit(ti_data, ti_discrete_columns)
        gx = self.global_transformer.transform(global_data).astype("float32")
        tx = self.ti_transformer.transform(ti_data).astype("float32")

        t0, t1, _ = _discrete_span(self.ti_transformer, "ti_skeleton_token")
        self.ti_skeleton_span = (t0, t1)
        self._build_models(gx.shape[1], tx.shape[1])

        dataset = TensorDataset(torch.from_numpy(gx), torch.from_numpy(tx))
        loader = DataLoader(dataset, batch_size=self.batch_size, shuffle=True)
        parameters = [p for module in self._all_modules() for p in module.parameters()]
        optimizer = Adam(parameters, weight_decay=self.l2scale)
        scaler = torch.amp.GradScaler("cuda", enabled=self._device.type == "cuda")
        self.loss_values = []

        for epoch in range(self.epochs):
            running = {"global": 0.0, "ti_skeleton": 0.0, "kl": 0.0}
            count = 0
            context_probability = self._context_probability(epoch)
            kw = self.kl_weight
            if self.kl_warmup_epochs > 0:
                kw *= min(1.0, (epoch + 1) / self.kl_warmup_epochs)

            for gb, tb in loader:
                gb, tb = gb.to(self._device), tb.to(self._device)
                full = torch.cat([gb, tb], dim=1)
                optimizer.zero_grad(set_to_none=True)
                with torch.amp.autocast("cuda", enabled=self._device.type == "cuda"):
                    mu, std, logvar = self.encoder(full)
                    z = mu + torch.randn_like(std) * std

                    graw, gsigma = self.global_decoder(z)
                    gpred = _activate(graw, self.global_transformer.output_info_list)
                    gctx = self.global_context_encoder(
                        self._mix_context(gb, gpred, context_probability)
                    )

                    traw, tsigma = self.ti_skeleton_decoder(
                        torch.cat([z, gctx], dim=1)
                    )
                    gl = _block_loss(
                        graw, gb, gsigma,
                        self.global_transformer.output_info_list,
                        self.loss_factor,
                    )
                    tl = _block_loss(
                        traw, tb, tsigma,
                        self.ti_transformer.output_info_list,
                        self.loss_factor,
                    )
                    kl = -0.5 * torch.sum(
                        1 + logvar - mu.square() - logvar.exp()
                    ) / full.size(0)
                    loss = (
                        self.global_loss_weight * gl
                        + self.ti_skeleton_loss_weight * tl
                        + kw * kl
                    )

                scaler.scale(loss).backward()
                scaler.unscale_(optimizer)
                torch.nn.utils.clip_grad_norm_(parameters, 1.0)
                scaler.step(optimizer)
                scaler.update()
                self.global_decoder.sigma.data.clamp_(0.01, 1.0)
                self.ti_skeleton_decoder.sigma.data.clamp_(0.01, 1.0)

                bsz = full.size(0)
                count += bsz
                running["global"] += float(gl.detach()) * bsz
                running["ti_skeleton"] += float(tl.detach()) * bsz
                running["kl"] += float(kl.detach()) * bsz

            record = {
                "epoch": epoch + 1,
                "global_loss": running["global"] / count,
                "ti_skeleton_loss": running["ti_skeleton"] / count,
                "kl_loss": running["kl"] / count,
                "predicted_context_probability": context_probability,
                "kl_weight": kw,
            }
            self.loss_values.append(record)
            if self.verbose and (
                epoch == 0 or (epoch + 1) % 25 == 0 or epoch + 1 == self.epochs
            ):
                total = (
                    self.global_loss_weight * record["global_loss"]
                    + self.ti_skeleton_loss_weight * record["ti_skeleton_loss"]
                    + kw * record["kl_loss"]
                )
                print(
                    f"Epoch {epoch + 1:4d}/{self.epochs} | "
                    f"loss {total:.3f} | ctx {context_probability:.2f}",
                    flush=True,
                )

        pd.DataFrame(self.loss_values).to_csv(
            os.path.join(self.root_folder, "entrance_vae_loss.csv"), index=False
        )

    @random_state
    def sample_ti_skeletons(
        self,
        samples,
        temperature=1.0,
        hard=True,
        max_independent_sites=None,
        max_ti_atoms=32,
    ):
        """Sample the production entrance variables: S and W_Ti."""
        for module in self._all_modules():
            module.eval()

        sp0, sp1, sp_categories = _discrete_span(
            self.global_transformer, "spg"
        )
        t0, t1, ti_categories = _discrete_span(
            self.ti_transformer, "ti_skeleton_token"
        )
        parsed_ti = [_parse_wp_token(x) for x in ti_categories]

        output_spg, output_tokens, valid_all = [], [], []
        stats = {
            "rows": int(samples),
            "invalid_space_group": 0,
            "no_compatible_ti_skeleton": 0,
        }
        generated = 0

        from pyxtal.symmetry import Group
        groups = {}
        with torch.no_grad():
            while generated < samples:
                n = min(self.batch_size, samples - generated)
                z = torch.randn(n, self.embedding_dim, device=self._device)
                graw, _ = self.global_decoder(z)
                gx = _activate(
                    graw,
                    self.global_transformer.output_info_list,
                    temperature=temperature,
                    hard=hard,
                )
                gctx = self.global_context_encoder(gx)
                traw, _ = self.ti_skeleton_decoder(torch.cat([z, gctx], dim=1))

                sp_ids = torch.argmax(gx[:, sp0:sp1], dim=1).cpu().numpy()
                allowed = torch.zeros(
                    (n, len(ti_categories)), dtype=torch.bool, device=self._device
                )
                row_valid = np.ones(n, dtype=bool)
                realized_spg = []

                for row, category in enumerate(sp_ids):
                    try:
                        spg = int(round(float(sp_categories[int(category)])))
                        group = groups.setdefault(spg, Group(spg))
                        mult = [int(group[i].multiplicity) for i in range(len(group))]
                    except Exception:
                        spg, mult = -1, []
                    realized_spg.append(spg)

                    if not 1 <= spg <= 230:
                        row_valid[row] = False
                        stats["invalid_space_group"] += 1
                        allowed[row, 0] = True
                        continue

                    for tid, token in enumerate(parsed_ti):
                        occupied = [w for w in token if w >= 0]
                        if not occupied or any(w >= len(mult) for w in occupied):
                            continue
                        if max_independent_sites is not None and (
                            len(occupied) > int(max_independent_sites)
                        ):
                            continue
                        n_ti = sum(mult[w] for w in occupied)
                        if 2 <= n_ti <= int(max_ti_atoms):
                            allowed[row, tid] = True

                    if not bool(allowed[row].any()):
                        row_valid[row] = False
                        stats["no_compatible_ti_skeleton"] += 1
                        allowed[row, 0] = True

                tx = _activate(
                    traw,
                    self.ti_transformer.output_info_list,
                    temperature=temperature,
                    hard=hard,
                    masks={(t0, t1): allowed},
                )
                tids = torch.argmax(tx[:, t0:t1], dim=1).cpu().numpy()
                output_spg.extend(realized_spg)
                output_tokens.extend(str(ti_categories[int(i)]) for i in tids)
                valid_all.extend(row_valid.tolist())
                generated += n

        return {
            "spg": np.asarray(output_spg[:samples], dtype=int),
            "ti_skeleton_token": np.asarray(output_tokens[:samples], dtype=object),
            "valid_mask": np.asarray(valid_all[:samples], dtype=bool),
            "stats": stats,
        }
