#!/usr/bin/env python3
"""
Convert tetrahedral SiO2 CIFs into a LEGO-Xtal-compatible ASE DB.

The resulting DB can be opened by:

    from pyxtal.db import database_topology
    db = database_topology("sio2_tetrahedral.db")
    xtals = db.get_all_xtals()

Additional row metadata
-----------------------
source_cif
cn_labels          comma-separated labels aligned with pyxtal.atom_sites
cn_labels_json     JSON list aligned with pyxtal.atom_sites
cn_multiplicities  JSON list of Wyckoff multiplicities
cn_wp_labels       JSON list of Wyckoff labels, e.g. ["4a", "8c"]
si_atoms
o_atoms
si_fraction
o_fraction
sio_cutoff
sio2_tetrahedral
dimension

Only ordered SiO2 structures whose PyXtal Wyckoff orbits are uniformly
Si(CN_O=4) or O(CN_Si=2) are written. Existing output DBs are not overwritten
unless --overwrite is supplied.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import os
from collections import Counter
from pathlib import Path

import numpy as np
from ase.db import connect
from pymatgen.analysis.graphs import StructureGraph
from pymatgen.analysis.local_env import CutOffDictNN
from pymatgen.core import Structure
from pyxtal import pyxtal
from pyxtal.db import database_topology


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Convert tetrahedral SiO2 CIFs to a LEGO-Xtal DB."
    )
    p.add_argument(
        "input",
        type=Path,
        help="Directory containing SiO2 CIFs, e.g. mp_sio2_tetrahedral/cifs",
    )
    p.add_argument(
        "-o", "--output",
        type=Path,
        default=Path("sio2_tetrahedral.db"),
        help="Output ASE/LEGO-Xtal database (default: sio2_tetrahedral.db)",
    )
    p.add_argument(
        "--sio-cutoff",
        type=float,
        default=2.15,
        help="Si-O coordination cutoff in Å (default: 2.15)",
    )
    p.add_argument(
        "--symprec",
        type=float,
        default=1.0e-3,
        help="Tolerance passed to pyxtal.from_seed (default: 1e-3)",
    )
    p.add_argument(
        "--max-atoms",
        type=int,
        default=1000,
        help="Reject cells larger than this (default: 1000)",
    )
    p.add_argument(
        "--max-wp",
        type=int,
        default=32,
        help="Reject structures with more independent Wyckoff sites "
             "(default: 32; training may later use a smaller value)",
    )
    p.add_argument(
        "--recursive",
        action="store_true",
        help="Search recursively for CIFs",
    )
    p.add_argument(
        "--overwrite",
        action="store_true",
        help="Replace an existing output DB",
    )
    p.add_argument(
        "--keep-nonuniform",
        action="store_true",
        help="Keep an orbit when equivalent atoms do not have identical CN; "
             "assign the modal CN. Not recommended for the first dataset.",
    )
    return p.parse_args()


def find_cifs(root: Path, recursive: bool) -> list[Path]:
    pattern = "**/*.cif" if recursive else "*.cif"
    return sorted(p for p in root.glob(pattern) if p.is_file())


def make_graph(structure: Structure, cutoff: float) -> StructureGraph:
    nn = CutOffDictNN({("Si", "O"): cutoff, ("O", "Si"): cutoff})
    if hasattr(StructureGraph, "from_local_env_strategy"):
        return StructureGraph.from_local_env_strategy(structure, nn)
    return StructureGraph.with_local_env_strategy(structure, nn)


def coordination_numbers(graph: StructureGraph) -> list[int]:
    return [len(graph.get_connected_sites(i)) for i in range(len(graph.structure))]


def frac_distance_matrix(frac_a: np.ndarray, frac_b: np.ndarray) -> np.ndarray:
    """
    Component-wise wrapped fractional-coordinate difference.

    This is only used to identify an exact symmetry-equivalent coordinate
    generated by PyXtal. Cartesian distances are evaluated afterward.
    """
    delta = frac_a[:, None, :] - frac_b[None, :, :]
    delta -= np.rint(delta)
    return delta


def match_xtal_sites_to_pmg(
    xtal_obj: pyxtal,
    pmg: Structure,
    cns: list[int],
    keep_nonuniform: bool,
) -> tuple[list[int], list[int], list[str]]:
    """
    Return one CN label, multiplicity, and WP label per pyxtal.atom_site.

    For each PyXtal orbit, generate its symmetry-equivalent fractional
    coordinates, match them to sites in xtal.to_pymatgen(), and verify that
    all members of the orbit have the same coordination number.
    """
    lattice = pmg.lattice
    pmg_frac = np.mod(np.asarray(pmg.frac_coords, dtype=float), 1.0)

    labels: list[int] = []
    multiplicities: list[int] = []
    wp_labels: list[str] = []

    for orbit_index, site in enumerate(xtal_obj.atom_sites):
        # PyXtal's WP object generates all equivalent coordinates from the
        # representative site position.
        orbit_frac = np.mod(
            np.asarray(site.wp.apply_ops(site.position), dtype=float),
            1.0,
        )

        matched_indices: list[int] = []
        for fcoord in orbit_frac:
            diffs = pmg_frac - fcoord
            diffs -= np.rint(diffs)
            cart = lattice.get_cartesian_coords(diffs)
            distances = np.linalg.norm(cart, axis=1)
            idx = int(np.argmin(distances))
            if float(distances[idx]) > 1.0e-3:
                raise ValueError(
                    f"orbit {orbit_index} ({site.wp.get_label()}): "
                    f"cannot match generated coordinate; nearest distance "
                    f"is {distances[idx]:.3e} Å"
                )
            matched_indices.append(idx)

        matched_indices = sorted(set(matched_indices))
        orbit_cns = [int(cns[i]) for i in matched_indices]
        counts = Counter(orbit_cns)

        if not orbit_cns:
            raise ValueError(
                f"orbit {orbit_index} ({site.wp.get_label()}): no atoms matched"
            )

        if len(counts) != 1:
            if not keep_nonuniform:
                raise ValueError(
                    f"orbit {orbit_index} ({site.wp.get_label()}) has "
                    f"nonuniform coordination {dict(counts)}"
                )
            label = counts.most_common(1)[0][0]
        else:
            label = orbit_cns[0]

        expected = 4 if site.specie == "Si" else 2 if site.specie == "O" else None
        if expected is None:
            raise ValueError(f"unexpected species {site.specie}")
        if label != expected:
            raise ValueError(
                f"orbit {orbit_index} ({site.specie}, {site.wp.get_label()}) "
                f"has CN={label}, expected {expected}"
            )

        labels.append(label)
        multiplicities.append(int(site.wp.multiplicity))
        wp_labels.append(str(site.wp.get_label()))

    return labels, multiplicities, wp_labels


def assign_target_coordination(
    xtal_obj: pyxtal,
    labels: list[int],
) -> None:
    """Attach persistent target-coordination labels to PyXtal atom sites."""
    if len(labels) != len(xtal_obj.atom_sites):
        raise ValueError(
            "Target-label count does not match atom-site count: "
            f"{len(labels)} labels for "
            f"{len(xtal_obj.atom_sites)} atom sites."
        )

    for index, (site, label) in enumerate(
        zip(xtal_obj.atom_sites, labels)
    ):
        label = int(label)

        expected = 4 if site.specie == "Si" else 2 if site.specie == "O" else None
        if expected is None or label != expected:
            raise ValueError(
                f"Invalid target coordination {label} for atom-site {index} "
                f"({site.specie}); expected {expected}."
            )

        if not hasattr(site, "property") or site.property is None:
            site.property = {}

        site.property["target_coordination"] = label


def make_kvp(
    xtal_obj: pyxtal,
    source: Path,
    labels: list[int],
    multiplicities: list[int],
    wp_labels: list[str],
    cutoff: float,
) -> dict:
    total = int(sum(multiplicities))
    n_si = int(sum(m for site, m in zip(xtal_obj.atom_sites, multiplicities) if site.specie == "Si"))
    n_o = int(sum(m for site, m in zip(xtal_obj.atom_sites, multiplicities) if site.specie == "O"))

    if total != n_si + n_o:
        raise ValueError("Si/O multiplicities do not sum to total atoms")
    if n_o != 2 * n_si:
        raise ValueError(f"not SiO2 stoichiometry after symmetry reconstruction: Si={n_si}, O={n_o}")

    return {
        "source_cif": source.name,
        "cn_labels": ",".join(map(str, labels)),
        "cn_labels_json": json.dumps(labels, separators=(",", ":")),
        "cn_multiplicities": json.dumps(multiplicities, separators=(",", ":")),
        "cn_wp_labels": json.dumps(wp_labels, separators=(",", ":")),
        "si_atoms": n_si,
        "o_atoms": n_o,
        "si_fraction": float(n_si / total),
        "o_fraction": float(n_o / total),
        "sio_cutoff": float(cutoff),
        "sio2_tetrahedral": 1,
        "dimension": 3,
    }


def write_report(path: Path, rows: list[dict]) -> None:
    fields = [
        "source_cif",
        "status",
        "reason",
        "db_id",
        "spg",
        "natoms",
        "n_wp",
        "wp_labels",
        "cn_labels",
        "multiplicities",
        "si_fraction",
        "o_fraction",
    ]
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)


def main() -> None:
    args = parse_args()
    cifs = find_cifs(args.input, args.recursive)
    if not cifs:
        raise SystemExit(f"No CIF files found in {args.input}")

    if args.output.exists():
        if not args.overwrite:
            raise SystemExit(
                f"{args.output} already exists. Use --overwrite to replace it."
            )
        args.output.unlink()

    args.output.parent.mkdir(parents=True, exist_ok=True)
    report_path = args.output.with_suffix(".conversion.csv")

    db = database_topology(str(args.output))
    report: list[dict] = []
    accepted = 0

    for count, cif in enumerate(cifs, start=1):
        row = {
            "source_cif": cif.name,
            "status": "rejected",
            "reason": "",
            "db_id": "",
            "spg": "",
            "natoms": "",
            "n_wp": "",
            "wp_labels": "",
            "cn_labels": "",
            "multiplicities": "",
            "si_fraction": "",
            "o_fraction": "",
        }

        try:
            pmg_input = Structure.from_file(cif, primitive=False, sort=False)

            if {e.symbol for e in pmg_input.composition.elements} != {"Si", "O"}:
                raise ValueError("not binary Si/O")
            reduced = pmg_input.composition.reduced_composition.as_dict()
            if reduced != {"Si": 1.0, "O": 2.0}:
                raise ValueError(f"not exact SiO2 stoichiometry: {reduced}")
            if not pmg_input.is_ordered:
                raise ValueError("disordered or partially occupied structure")
            if len(pmg_input) > args.max_atoms:
                raise ValueError(
                    f"too many atoms: {len(pmg_input)} > {args.max_atoms}"
                )

            xtal_obj = pyxtal()
            xtal_obj.from_seed(pmg_input, tol=args.symprec)

            if not xtal_obj.valid:
                raise ValueError("PyXtal conversion returned invalid structure")
            if len(xtal_obj.atom_sites) > args.max_wp:
                raise ValueError(
                    f"too many Wyckoff sites: {len(xtal_obj.atom_sites)} "
                    f"> {args.max_wp}"
                )

            # Recompute CN on the exact structure PyXtal will store, ensuring
            # that label order and stored geometry are consistent.
            pmg = xtal_obj.to_pymatgen()
            graph = make_graph(pmg, args.sio_cutoff)
            cns = coordination_numbers(graph)

            labels, multiplicities, wp_labels = match_xtal_sites_to_pmg(
                xtal_obj,
                pmg,
                cns,
                keep_nonuniform=args.keep_nonuniform,
            )

            assign_target_coordination(
                xtal_obj,
                labels,
            )

            kvp = make_kvp(
                xtal_obj,
                cif,
                labels,
                multiplicities,
                wp_labels,
                args.sio_cutoff,
            )

            db.add_xtal(xtal_obj, kvp=kvp)

            # The most recently written row is the one just added.
            db_id = db.db.count()
            accepted += 1

            row.update(
                {
                    "status": "written",
                    "db_id": db_id,
                    "spg": xtal_obj.group.number,
                    "natoms": int(sum(xtal_obj.numIons)),
                    "n_wp": len(xtal_obj.atom_sites),
                    "wp_labels": json.dumps(wp_labels),
                    "cn_labels": json.dumps(labels),
                    "multiplicities": json.dumps(multiplicities),
                    "si_fraction": kvp["si_fraction"],
                    "o_fraction": kvp["o_fraction"],
                }
            )

        except Exception as exc:
            row["reason"] = f"{type(exc).__name__}: {exc}"

        report.append(row)

        if count % 50 == 0 or count == len(cifs):
            print(
                f"[{count}/{len(cifs)}] written={accepted}, "
                f"rejected={count - accepted}",
                flush=True,
            )
            write_report(report_path, report)

    write_report(report_path, report)

    # Verify that LEGO-Xtal's normal loader can reconstruct every row.
    verify_db = database_topology(str(args.output))
    loaded = verify_db.get_all_xtals(include_energy=False)

    missing_labels = []
    invalid_labels = []
    invalid_templates = []

    for structure_index, xtal_obj in enumerate(loaded):
        labels = []

        for site_index, site in enumerate(xtal_obj.atom_sites):
            value = getattr(site, "target_coordination", None)

            if value is None:
                value = (getattr(site, "property", {}) or {}).get(
                    "target_coordination"
                )

            if value is None:
                missing_labels.append(
                    (
                        structure_index,
                        site_index,
                        site.wp.get_label(),
                    )
                )
                continue

            value = int(value)
            labels.append(value)

            expected = 4 if site.specie == "Si" else 2 if site.specie == "O" else None
            if value != expected:
                invalid_labels.append(
                    (
                        structure_index,
                        site_index,
                        value,
                    )
                )

        expected_labels = [4 if site.specie == "Si" else 2 for site in xtal_obj.atom_sites]
        if labels and labels != expected_labels:
            invalid_templates.append((structure_index, labels, expected_labels))

    print("\nSummary")
    print("-------")
    print(f"Input CIFs:          {len(cifs)}")
    print(f"Rows written:        {accepted}")
    print(f"LEGO-Xtal loadable:  {len(loaded)}")
    print(f"Rejected:            {len(cifs) - accepted}")
    print(f"Missing labels:      {len(missing_labels)}")
    print(f"Invalid labels:      {len(invalid_labels)}")
    print(f"Invalid templates:    {len(invalid_templates)}")
    print(f"Database:            {args.output.resolve()}")
    print(f"Conversion report:   {report_path.resolve()}")

    if len(loaded) != accepted:
        raise SystemExit(
            "Verification failed: the number reloadable through "
            "database_topology differs from the number written."
        )

    if missing_labels:
        print("\nFirst missing labels:")
        for item in missing_labels[:10]:
            print(item)

        raise SystemExit(
            "Verification failed: target_coordination was not preserved "
            "through database serialization."
        )

    if invalid_labels:
        raise SystemExit(
            "Verification failed: invalid target coordination labels "
            "were found after reload."
        )

    if invalid_templates:
        raise SystemExit(
            "Verification failed: some reloaded structures no longer carry "
            "the Si->4 / O->2 template."
        )

if __name__ == "__main__":
    main()

